services:
  db:
    image: postgres:15-alpine
    container_name: orca-db
    restart: always
    env_file:
      - ../server/.env
    volumes:
      - orca-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    container_name: orca-server
    restart: always
    depends_on:
      - db
    env_file:
      - ../server/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432

  client:
    build:
      context: ../client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://api.orcacli.codes}
    container_name: orca-client
    restart: always
    depends_on:
      - server
    env_file:
      - ../client/.env

  nginx:
    image: nginx:alpine
    container_name: orca-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - server

volumes:
  orca-db-data:
