version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/orca"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "cargo"
    directory: "/cli-commit"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
